[package]
name = "rusty_vision"
version = "0.1.0"
authors = ["Jules Youngberg <julesdayoungberg@gmail.com>"]
edition = "2018"

[dependencies]
bytemuck = { version = "1.4", features = [ "derive" ] }
nannou = "0.15"
notify = "4.0.12"
path-slash = "0.1.3"
rayon = "1.4"
regex = "1"
shaderc = "0.6"
